Fix autopkgtest failures on arches other than amd64
autopkgtest was failing on all arches other than amd64 due to the
following reason:
 autopkgtest [06:39:25]: test snow-chibi: [-----------------------
 .ERROR: couldn't find include: "chibi/sqlite3.so"

Upon reproducing the error locally, I determined it was missing the
pkgconf dependency in d/t/control. This commit adds the dependency.